branch-defaults:
  lesson-2-exercise-1:
    environment: node-express-env
    group_suffix: null
global:
  application_name: DeployAwsCli
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-west-2
  default_environment: node-express-env
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default 
  repository: null
  sc: git
  workspace_type: Application
